namespace GUI
{
    partial class Form_Main
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form_Main));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges12 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges13 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.StateProperties();
            Bunifu.UI.WinForms.BunifuAnimatorNS.Animation animation1 = new Bunifu.UI.WinForms.BunifuAnimatorNS.Animation();
            this.navigationBar = new Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel();
            this.btnReport = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLogout = new Bunifu.UI.WinForms.BunifuImageButton();
            this.btnSettings = new Bunifu.UI.WinForms.BunifuImageButton();
            this.btnCustomers = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEmployee = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSell = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnBooks = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnHome = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuDragControl1 = new Bunifu.Framework.UI.BunifuDragControl(this.components);
            this.background = new System.Windows.Forms.Panel();
            this.panelSettings = new System.Windows.Forms.Panel();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.reportDropdown = new System.Windows.Forms.Panel();
            this.btnDebt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnInventory = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.sellDropdown = new System.Windows.Forms.Panel();
            this.btnTabDebt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTabInvoice = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnTabSell = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panelControls = new System.Windows.Forms.Panel();
            this.Shadow = new System.Windows.Forms.PictureBox();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.DropdownAnimation = new Bunifu.UI.WinForms.BunifuTransition(this.components);
            this.bunifuToolTip1 = new Bunifu.UI.WinForms.BunifuToolTip(this.components);
            this.navigationBar.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.background.SuspendLayout();
            this.panelSettings.SuspendLayout();
            this.reportDropdown.SuspendLayout();
            this.sellDropdown.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.Shadow)).BeginInit();
            this.SuspendLayout();
            // 
            // navigationBar
            // 
            this.navigationBar.BackColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.navigationBar.BorderColor = System.Drawing.Color.Transparent;
            this.navigationBar.Controls.Add(this.btnReport);
            this.navigationBar.Controls.Add(this.btnLogout);
            this.navigationBar.Controls.Add(this.btnSettings);
            this.navigationBar.Controls.Add(this.btnCustomers);
            this.navigationBar.Controls.Add(this.btnEmployee);
            this.navigationBar.Controls.Add(this.btnSell);
            this.navigationBar.Controls.Add(this.btnBooks);
            this.navigationBar.Controls.Add(this.btnHome);
            this.navigationBar.Controls.Add(this.pictureBox1);
            this.navigationBar.Controls.Add(this.label1);
            this.DropdownAnimation.SetDecoration(this.navigationBar, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.navigationBar.Dock = System.Windows.Forms.DockStyle.Top;
            this.navigationBar.Location = new System.Drawing.Point(0, 0);
            this.navigationBar.Name = "navigationBar";
            this.navigationBar.PanelColor = System.Drawing.Color.Empty;
            this.navigationBar.ShadowDept = 2;
            this.navigationBar.ShadowTopLeftVisible = false;
            this.navigationBar.Size = new System.Drawing.Size(1363, 91);
            this.navigationBar.TabIndex = 1;
            this.bunifuToolTip1.SetToolTip(this.navigationBar, "");
            this.bunifuToolTip1.SetToolTipIcon(this.navigationBar, null);
            this.bunifuToolTip1.SetToolTipTitle(this.navigationBar, "");
            this.navigationBar.Paint += new System.Windows.Forms.PaintEventHandler(this.navigationBar_Paint);
            // 
            // btnReport
            // 
            this.btnReport.AllowToggling = false;
            this.btnReport.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnReport.AnimationSpeed = 200;
            this.btnReport.AutoGenerateColors = false;
            this.btnReport.BackColor = System.Drawing.Color.Transparent;
            this.btnReport.BackColor1 = System.Drawing.Color.Transparent;
            this.btnReport.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnReport.BackgroundImage")));
            this.btnReport.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnReport.ButtonText = "Report";
            this.btnReport.ButtonTextMarginLeft = 0;
            this.btnReport.ColorContrastOnClick = 45;
            this.btnReport.ColorContrastOnHover = 45;
            this.btnReport.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnReport.CustomizableEdges = borderEdges1;
            this.DropdownAnimation.SetDecoration(this.btnReport, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.btnReport.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnReport.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnReport.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnReport.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnReport.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnReport.Font = new System.Drawing.Font("Amatic SC", 27.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnReport.ForeColor = System.Drawing.Color.White;
            this.btnReport.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnReport.IconMarginLeft = 0;
            this.btnReport.IconPadding = 10;
            this.btnReport.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnReport.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnReport.IdleBorderRadius = 3;
            this.btnReport.IdleBorderThickness = 1;
            this.btnReport.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnReport.IdleIconLeftImage = null;
            this.btnReport.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btnReport.IdleIconRightImage")));
            this.btnReport.IndicateFocus = true;
            this.btnReport.Location = new System.Drawing.Point(1023, 19);
            this.btnReport.Margin = new System.Windows.Forms.Padding(4);
            this.btnReport.Name = "btnReport";
            stateProperties1.BorderColor = System.Drawing.Color.Transparent;
            stateProperties1.BorderRadius = 3;
            stateProperties1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties1.BorderThickness = 1;
            stateProperties1.FillColor = System.Drawing.Color.Transparent;
            stateProperties1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            stateProperties1.IconLeftImage = null;
            stateProperties1.IconRightImage = null;
            this.btnReport.onHoverState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.Transparent;
            stateProperties2.BorderRadius = 3;
            stateProperties2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties2.BorderThickness = 1;
            stateProperties2.FillColor = System.Drawing.Color.Transparent;
            stateProperties2.ForeColor = System.Drawing.Color.White;
            stateProperties2.IconLeftImage = null;
            stateProperties2.IconRightImage = null;
            this.btnReport.OnPressedState = stateProperties2;
            this.btnReport.Size = new System.Drawing.Size(140, 48);
            this.btnReport.TabIndex = 36;
            this.btnReport.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnReport.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.btnReport, "");
            this.bunifuToolTip1.SetToolTipIcon(this.btnReport, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnReport, "");
            this.btnReport.UseDefaultRadiusAndThickness = true;
            this.btnReport.Click += new System.EventHandler(this.btnReport_Click);
            this.btnReport.MouseEnter += new System.EventHandler(this.btnReport_MouseEnter);
            // 
            // btnLogout
            // 
            this.btnLogout.ActiveImage = ((System.Drawing.Image)(resources.GetObject("btnLogout.ActiveImage")));
            this.btnLogout.AllowAnimations = true;
            this.btnLogout.AllowBuffering = false;
            this.btnLogout.AllowZooming = true;
            this.btnLogout.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnLogout.BackColor = System.Drawing.Color.Transparent;
            this.DropdownAnimation.SetDecoration(this.btnLogout, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.btnLogout.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnLogout.ErrorImage")));
            this.btnLogout.FadeWhenInactive = false;
            this.btnLogout.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnLogout.Image = ((System.Drawing.Image)(resources.GetObject("btnLogout.Image")));
            this.btnLogout.ImageActive = ((System.Drawing.Image)(resources.GetObject("btnLogout.ImageActive")));
            this.btnLogout.ImageLocation = null;
            this.btnLogout.ImageMargin = 15;
            this.btnLogout.ImageSize = new System.Drawing.Size(35, 38);
            this.btnLogout.ImageZoomSize = new System.Drawing.Size(50, 53);
            this.btnLogout.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnLogout.InitialImage")));
            this.btnLogout.Location = new System.Drawing.Point(1283, 20);
            this.btnLogout.Name = "btnLogout";
            this.btnLogout.Rotation = 0;
            this.btnLogout.ShowActiveImage = true;
            this.btnLogout.ShowCursorChanges = true;
            this.btnLogout.ShowImageBorders = true;
            this.btnLogout.ShowSizeMarkers = false;
            this.btnLogout.Size = new System.Drawing.Size(50, 53);
            this.btnLogout.TabIndex = 35;
            this.bunifuToolTip1.SetToolTip(this.btnLogout, "Log Out");
            this.bunifuToolTip1.SetToolTipIcon(this.btnLogout, null);
            this.btnLogout.ToolTipText = "";
            this.bunifuToolTip1.SetToolTipTitle(this.btnLogout, "");
            this.btnLogout.WaitOnLoad = false;
            this.btnLogout.Zoom = 15;
            this.btnLogout.ZoomSpeed = 10;
            // 
            // btnSettings
            // 
            this.btnSettings.ActiveImage = ((System.Drawing.Image)(resources.GetObject("btnSettings.ActiveImage")));
            this.btnSettings.AllowAnimations = true;
            this.btnSettings.AllowBuffering = false;
            this.btnSettings.AllowZooming = true;
            this.btnSettings.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.btnSettings.BackColor = System.Drawing.Color.Transparent;
            this.DropdownAnimation.SetDecoration(this.btnSettings, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.btnSettings.ErrorImage = ((System.Drawing.Image)(resources.GetObject("btnSettings.ErrorImage")));
            this.btnSettings.FadeWhenInactive = false;
            this.btnSettings.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.btnSettings.Image = ((System.Drawing.Image)(resources.GetObject("btnSettings.Image")));
            this.btnSettings.ImageActive = ((System.Drawing.Image)(resources.GetObject("btnSettings.ImageActive")));
            this.btnSettings.ImageLocation = null;
            this.btnSettings.ImageMargin = 15;
            this.btnSettings.ImageSize = new System.Drawing.Size(35, 38);
            this.btnSettings.ImageZoomSize = new System.Drawing.Size(50, 53);
            this.btnSettings.InitialImage = ((System.Drawing.Image)(resources.GetObject("btnSettings.InitialImage")));
            this.btnSettings.Location = new System.Drawing.Point(1213, 20);
            this.btnSettings.Name = "btnSettings";
            this.btnSettings.Rotation = 0;
            this.btnSettings.ShowActiveImage = true;
            this.btnSettings.ShowCursorChanges = true;
            this.btnSettings.ShowImageBorders = true;
            this.btnSettings.ShowSizeMarkers = false;
            this.btnSettings.Size = new System.Drawing.Size(50, 53);
            this.btnSettings.TabIndex = 34;
            this.bunifuToolTip1.SetToolTip(this.btnSettings, "Settings");
            this.bunifuToolTip1.SetToolTipIcon(this.btnSettings, null);
            this.btnSettings.ToolTipText = "";
            this.bunifuToolTip1.SetToolTipTitle(this.btnSettings, "");
            this.btnSettings.WaitOnLoad = false;
            this.btnSettings.Zoom = 15;
            this.btnSettings.ZoomSpeed = 10;
            this.btnSettings.Click += new System.EventHandler(this.btnSettings_Click);
            // 
            // btnCustomers
            // 
            this.btnCustomers.AllowToggling = false;
            this.btnCustomers.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnCustomers.AnimationSpeed = 200;
            this.btnCustomers.AutoGenerateColors = false;
            this.btnCustomers.BackColor = System.Drawing.Color.Transparent;
            this.btnCustomers.BackColor1 = System.Drawing.Color.Transparent;
            this.btnCustomers.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCustomers.BackgroundImage")));
            this.btnCustomers.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCustomers.ButtonText = "Customers";
            this.btnCustomers.ButtonTextMarginLeft = 0;
            this.btnCustomers.ColorContrastOnClick = 45;
            this.btnCustomers.ColorContrastOnHover = 45;
            this.btnCustomers.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnCustomers.CustomizableEdges = borderEdges2;
            this.DropdownAnimation.SetDecoration(this.btnCustomers, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.btnCustomers.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCustomers.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCustomers.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCustomers.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCustomers.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCustomers.Font = new System.Drawing.Font("Amatic SC", 27.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnCustomers.ForeColor = System.Drawing.Color.White;
            this.btnCustomers.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCustomers.IconMarginLeft = 0;
            this.btnCustomers.IconPadding = 10;
            this.btnCustomers.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnCustomers.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnCustomers.IdleBorderRadius = 3;
            this.btnCustomers.IdleBorderThickness = 1;
            this.btnCustomers.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnCustomers.IdleIconLeftImage = null;
            this.btnCustomers.IdleIconRightImage = null;
            this.btnCustomers.IndicateFocus = true;
            this.btnCustomers.Location = new System.Drawing.Point(874, 19);
            this.btnCustomers.Margin = new System.Windows.Forms.Padding(4);
            this.btnCustomers.Name = "btnCustomers";
            stateProperties3.BorderColor = System.Drawing.Color.Transparent;
            stateProperties3.BorderRadius = 3;
            stateProperties3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties3.BorderThickness = 1;
            stateProperties3.FillColor = System.Drawing.Color.Transparent;
            stateProperties3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            stateProperties3.IconLeftImage = null;
            stateProperties3.IconRightImage = null;
            this.btnCustomers.onHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Transparent;
            stateProperties4.BorderRadius = 3;
            stateProperties4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties4.BorderThickness = 1;
            stateProperties4.FillColor = System.Drawing.Color.Transparent;
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.IconLeftImage = null;
            stateProperties4.IconRightImage = null;
            this.btnCustomers.OnPressedState = stateProperties4;
            this.btnCustomers.Size = new System.Drawing.Size(125, 48);
            this.btnCustomers.TabIndex = 32;
            this.btnCustomers.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCustomers.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.btnCustomers, "");
            this.bunifuToolTip1.SetToolTipIcon(this.btnCustomers, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnCustomers, "");
            this.btnCustomers.UseDefaultRadiusAndThickness = true;
            this.btnCustomers.Click += new System.EventHandler(this.btnCustomers_Click);
            // 
            // btnEmployee
            // 
            this.btnEmployee.AllowToggling = false;
            this.btnEmployee.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnEmployee.AnimationSpeed = 200;
            this.btnEmployee.AutoGenerateColors = false;
            this.btnEmployee.BackColor = System.Drawing.Color.Transparent;
            this.btnEmployee.BackColor1 = System.Drawing.Color.Transparent;
            this.btnEmployee.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEmployee.BackgroundImage")));
            this.btnEmployee.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEmployee.ButtonText = "Employee";
            this.btnEmployee.ButtonTextMarginLeft = 0;
            this.btnEmployee.ColorContrastOnClick = 45;
            this.btnEmployee.ColorContrastOnHover = 45;
            this.btnEmployee.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnEmployee.CustomizableEdges = borderEdges3;
            this.DropdownAnimation.SetDecoration(this.btnEmployee, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.btnEmployee.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEmployee.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEmployee.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEmployee.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEmployee.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEmployee.Font = new System.Drawing.Font("Amatic SC", 27.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnEmployee.ForeColor = System.Drawing.Color.White;
            this.btnEmployee.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnEmployee.IconMarginLeft = 0;
            this.btnEmployee.IconPadding = 10;
            this.btnEmployee.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnEmployee.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnEmployee.IdleBorderRadius = 3;
            this.btnEmployee.IdleBorderThickness = 1;
            this.btnEmployee.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnEmployee.IdleIconLeftImage = null;
            this.btnEmployee.IdleIconRightImage = null;
            this.btnEmployee.IndicateFocus = true;
            this.btnEmployee.Location = new System.Drawing.Point(725, 19);
            this.btnEmployee.Margin = new System.Windows.Forms.Padding(4);
            this.btnEmployee.Name = "btnEmployee";
            stateProperties5.BorderColor = System.Drawing.Color.Transparent;
            stateProperties5.BorderRadius = 3;
            stateProperties5.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties5.BorderThickness = 1;
            stateProperties5.FillColor = System.Drawing.Color.Transparent;
            stateProperties5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            stateProperties5.IconLeftImage = null;
            stateProperties5.IconRightImage = null;
            this.btnEmployee.onHoverState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.Transparent;
            stateProperties6.BorderRadius = 3;
            stateProperties6.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties6.BorderThickness = 1;
            stateProperties6.FillColor = System.Drawing.Color.Transparent;
            stateProperties6.ForeColor = System.Drawing.Color.White;
            stateProperties6.IconLeftImage = null;
            stateProperties6.IconRightImage = null;
            this.btnEmployee.OnPressedState = stateProperties6;
            this.btnEmployee.Size = new System.Drawing.Size(111, 48);
            this.btnEmployee.TabIndex = 31;
            this.btnEmployee.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEmployee.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.btnEmployee, "");
            this.bunifuToolTip1.SetToolTipIcon(this.btnEmployee, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnEmployee, "");
            this.btnEmployee.UseDefaultRadiusAndThickness = true;
            this.btnEmployee.Click += new System.EventHandler(this.btnEmployee_Click);
            // 
            // btnSell
            // 
            this.btnSell.AllowToggling = false;
            this.btnSell.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnSell.AnimationSpeed = 200;
            this.btnSell.AutoGenerateColors = false;
            this.btnSell.BackColor = System.Drawing.Color.Transparent;
            this.btnSell.BackColor1 = System.Drawing.Color.Transparent;
            this.btnSell.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSell.BackgroundImage")));
            this.btnSell.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSell.ButtonText = "Sell";
            this.btnSell.ButtonTextMarginLeft = 0;
            this.btnSell.ColorContrastOnClick = 45;
            this.btnSell.ColorContrastOnHover = 45;
            this.btnSell.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnSell.CustomizableEdges = borderEdges4;
            this.DropdownAnimation.SetDecoration(this.btnSell, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.btnSell.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSell.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSell.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSell.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSell.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSell.Font = new System.Drawing.Font("Amatic SC", 27.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnSell.ForeColor = System.Drawing.Color.White;
            this.btnSell.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSell.IconMarginLeft = 0;
            this.btnSell.IconPadding = 10;
            this.btnSell.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSell.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnSell.IdleBorderRadius = 3;
            this.btnSell.IdleBorderThickness = 1;
            this.btnSell.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnSell.IdleIconLeftImage = null;
            this.btnSell.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btnSell.IdleIconRightImage")));
            this.btnSell.IndicateFocus = true;
            this.btnSell.Location = new System.Drawing.Point(590, 19);
            this.btnSell.Margin = new System.Windows.Forms.Padding(4);
            this.btnSell.Name = "btnSell";
            stateProperties7.BorderColor = System.Drawing.Color.Transparent;
            stateProperties7.BorderRadius = 3;
            stateProperties7.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties7.BorderThickness = 1;
            stateProperties7.FillColor = System.Drawing.Color.Transparent;
            stateProperties7.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            stateProperties7.IconLeftImage = null;
            stateProperties7.IconRightImage = null;
            this.btnSell.onHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Transparent;
            stateProperties8.BorderRadius = 3;
            stateProperties8.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties8.BorderThickness = 1;
            stateProperties8.FillColor = System.Drawing.Color.Transparent;
            stateProperties8.ForeColor = System.Drawing.Color.White;
            stateProperties8.IconLeftImage = null;
            stateProperties8.IconRightImage = null;
            this.btnSell.OnPressedState = stateProperties8;
            this.btnSell.Size = new System.Drawing.Size(117, 48);
            this.btnSell.TabIndex = 30;
            this.btnSell.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSell.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.btnSell, "");
            this.bunifuToolTip1.SetToolTipIcon(this.btnSell, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnSell, "");
            this.btnSell.UseDefaultRadiusAndThickness = true;
            this.btnSell.Click += new System.EventHandler(this.btnSell_Click);
            // 
            // btnBooks
            // 
            this.btnBooks.AllowToggling = false;
            this.btnBooks.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnBooks.AnimationSpeed = 200;
            this.btnBooks.AutoGenerateColors = false;
            this.btnBooks.BackColor = System.Drawing.Color.Transparent;
            this.btnBooks.BackColor1 = System.Drawing.Color.Transparent;
            this.btnBooks.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBooks.BackgroundImage")));
            this.btnBooks.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBooks.ButtonText = "Books";
            this.btnBooks.ButtonTextMarginLeft = 0;
            this.btnBooks.ColorContrastOnClick = 45;
            this.btnBooks.ColorContrastOnHover = 45;
            this.btnBooks.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnBooks.CustomizableEdges = borderEdges5;
            this.DropdownAnimation.SetDecoration(this.btnBooks, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.btnBooks.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBooks.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBooks.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBooks.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBooks.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBooks.Font = new System.Drawing.Font("Amatic SC", 27.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnBooks.ForeColor = System.Drawing.Color.White;
            this.btnBooks.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnBooks.IconMarginLeft = 0;
            this.btnBooks.IconPadding = 10;
            this.btnBooks.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnBooks.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnBooks.IdleBorderRadius = 3;
            this.btnBooks.IdleBorderThickness = 1;
            this.btnBooks.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnBooks.IdleIconLeftImage = null;
            this.btnBooks.IdleIconRightImage = null;
            this.btnBooks.IndicateFocus = true;
            this.btnBooks.Location = new System.Drawing.Point(485, 19);
            this.btnBooks.Margin = new System.Windows.Forms.Padding(4);
            this.btnBooks.Name = "btnBooks";
            stateProperties9.BorderColor = System.Drawing.Color.Transparent;
            stateProperties9.BorderRadius = 3;
            stateProperties9.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties9.BorderThickness = 1;
            stateProperties9.FillColor = System.Drawing.Color.Transparent;
            stateProperties9.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            stateProperties9.IconLeftImage = null;
            stateProperties9.IconRightImage = null;
            this.btnBooks.onHoverState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.Transparent;
            stateProperties10.BorderRadius = 3;
            stateProperties10.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties10.BorderThickness = 1;
            stateProperties10.FillColor = System.Drawing.Color.Transparent;
            stateProperties10.ForeColor = System.Drawing.Color.White;
            stateProperties10.IconLeftImage = null;
            stateProperties10.IconRightImage = null;
            this.btnBooks.OnPressedState = stateProperties10;
            this.btnBooks.Size = new System.Drawing.Size(87, 48);
            this.btnBooks.TabIndex = 29;
            this.btnBooks.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBooks.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.btnBooks, "");
            this.bunifuToolTip1.SetToolTipIcon(this.btnBooks, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnBooks, "");
            this.btnBooks.UseDefaultRadiusAndThickness = true;
            this.btnBooks.Click += new System.EventHandler(this.btnBooks_Click);
            // 
            // btnHome
            // 
            this.btnHome.AllowToggling = false;
            this.btnHome.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.btnHome.AnimationSpeed = 200;
            this.btnHome.AutoGenerateColors = false;
            this.btnHome.BackColor = System.Drawing.Color.Transparent;
            this.btnHome.BackColor1 = System.Drawing.Color.Transparent;
            this.btnHome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHome.BackgroundImage")));
            this.btnHome.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.ButtonText = "Home";
            this.btnHome.ButtonTextMarginLeft = 0;
            this.btnHome.ColorContrastOnClick = 45;
            this.btnHome.ColorContrastOnHover = 45;
            this.btnHome.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnHome.CustomizableEdges = borderEdges6;
            this.DropdownAnimation.SetDecoration(this.btnHome, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.btnHome.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHome.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHome.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHome.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHome.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHome.Font = new System.Drawing.Font("Amatic SC", 27.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(163)));
            this.btnHome.ForeColor = System.Drawing.Color.White;
            this.btnHome.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnHome.IconMarginLeft = 40;
            this.btnHome.IconPadding = 10;
            this.btnHome.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnHome.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnHome.IdleBorderRadius = 3;
            this.btnHome.IdleBorderThickness = 1;
            this.btnHome.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnHome.IdleIconLeftImage = null;
            this.btnHome.IdleIconRightImage = null;
            this.btnHome.IndicateFocus = true;
            this.btnHome.Location = new System.Drawing.Point(361, 18);
            this.btnHome.Margin = new System.Windows.Forms.Padding(4);
            this.btnHome.Name = "btnHome";
            stateProperties11.BorderColor = System.Drawing.Color.Transparent;
            stateProperties11.BorderRadius = 3;
            stateProperties11.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties11.BorderThickness = 1;
            stateProperties11.FillColor = System.Drawing.Color.Transparent;
            stateProperties11.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(255)))), ((int)(((byte)(0)))));
            stateProperties11.IconLeftImage = null;
            stateProperties11.IconRightImage = null;
            this.btnHome.onHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Transparent;
            stateProperties12.BorderRadius = 3;
            stateProperties12.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties12.BorderThickness = 1;
            stateProperties12.FillColor = System.Drawing.Color.Transparent;
            stateProperties12.ForeColor = System.Drawing.Color.White;
            stateProperties12.IconLeftImage = null;
            stateProperties12.IconRightImage = null;
            this.btnHome.OnPressedState = stateProperties12;
            this.btnHome.Size = new System.Drawing.Size(76, 49);
            this.btnHome.TabIndex = 28;
            this.btnHome.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHome.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.btnHome, "");
            this.bunifuToolTip1.SetToolTipIcon(this.btnHome, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnHome, "");
            this.btnHome.UseDefaultRadiusAndThickness = true;
            this.btnHome.Click += new System.EventHandler(this.btnHome_Click);
            // 
            // pictureBox1
            // 
            this.DropdownAnimation.SetDecoration(this.pictureBox1, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(15, 21);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(50, 49);
            this.pictureBox1.TabIndex = 1;
            this.pictureBox1.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.pictureBox1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.pictureBox1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.pictureBox1, "");
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.DropdownAnimation.SetDecoration(this.label1, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.label1.Font = new System.Drawing.Font("Dream Meadow", 36F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(77)));
            this.label1.ForeColor = System.Drawing.Color.White;
            this.label1.Location = new System.Drawing.Point(71, 12);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(226, 64);
            this.label1.TabIndex = 0;
            this.label1.Text = "Santa Monica";
            this.bunifuToolTip1.SetToolTip(this.label1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.label1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.label1, "");
            // 
            // bunifuDragControl1
            // 
            this.bunifuDragControl1.Fixed = true;
            this.bunifuDragControl1.Horizontal = true;
            this.bunifuDragControl1.TargetControl = this.background;
            this.bunifuDragControl1.Vertical = true;
            // 
            // background
            // 
            this.background.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.background.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("background.BackgroundImage")));
            this.background.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.background.Controls.Add(this.panelSettings);
            this.background.Controls.Add(this.reportDropdown);
            this.background.Controls.Add(this.sellDropdown);
            this.background.Controls.Add(this.panelControls);
            this.background.Controls.Add(this.Shadow);
            this.DropdownAnimation.SetDecoration(this.background, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.background.Location = new System.Drawing.Point(-23, 88);
            this.background.Name = "background";
            this.background.Size = new System.Drawing.Size(1480, 696);
            this.background.TabIndex = 2;
            this.bunifuToolTip1.SetToolTip(this.background, "");
            this.bunifuToolTip1.SetToolTipIcon(this.background, null);
            this.bunifuToolTip1.SetToolTipTitle(this.background, "");
            // 
            // panelSettings
            // 
            this.panelSettings.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.panelSettings.BackColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.panelSettings.Controls.Add(this.bunifuButton1);
            this.panelSettings.Controls.Add(this.bunifuButton2);
            this.DropdownAnimation.SetDecoration(this.panelSettings, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.panelSettings.Location = new System.Drawing.Point(1204, 0);
            this.panelSettings.Name = "panelSettings";
            this.panelSettings.Size = new System.Drawing.Size(107, 106);
            this.panelSettings.TabIndex = 8;
            this.bunifuToolTip1.SetToolTip(this.panelSettings, "");
            this.bunifuToolTip1.SetToolTipIcon(this.panelSettings, null);
            this.bunifuToolTip1.SetToolTipTitle(this.panelSettings, "");
            this.panelSettings.Visible = false;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Price";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges7;
            this.DropdownAnimation.SetDecoration(this.bunifuButton1, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Futura Lt BT", 18F);
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.IdleBorderRadius = 3;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(3, 56);
            this.bunifuButton1.Name = "bunifuButton1";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties13.BorderRadius = 3;
            stateProperties13.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties13.BorderThickness = 1;
            stateProperties13.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties13.ForeColor = System.Drawing.Color.White;
            stateProperties13.IconLeftImage = null;
            stateProperties13.IconRightImage = null;
            this.bunifuButton1.onHoverState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties14.BorderRadius = 3;
            stateProperties14.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties14.BorderThickness = 1;
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties14.ForeColor = System.Drawing.Color.White;
            stateProperties14.IconLeftImage = null;
            stateProperties14.IconRightImage = null;
            this.bunifuButton1.OnPressedState = stateProperties14;
            this.bunifuButton1.Size = new System.Drawing.Size(101, 44);
            this.bunifuButton1.TabIndex = 6;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.bunifuButton1, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButton1, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButton1, "");
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Rule";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges8;
            this.DropdownAnimation.SetDecoration(this.bunifuButton2, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Futura Lt BT", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.IdleBorderRadius = 3;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(3, 3);
            this.bunifuButton2.Name = "bunifuButton2";
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.BorderRadius = 3;
            stateProperties15.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties15.BorderThickness = 1;
            stateProperties15.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.ForeColor = System.Drawing.Color.White;
            stateProperties15.IconLeftImage = null;
            stateProperties15.IconRightImage = null;
            this.bunifuButton2.onHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties16.BorderRadius = 3;
            stateProperties16.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties16.BorderThickness = 1;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties16.ForeColor = System.Drawing.Color.White;
            stateProperties16.IconLeftImage = null;
            stateProperties16.IconRightImage = null;
            this.bunifuButton2.OnPressedState = stateProperties16;
            this.bunifuButton2.Size = new System.Drawing.Size(101, 47);
            this.bunifuButton2.TabIndex = 5;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.bunifuButton2, "");
            this.bunifuToolTip1.SetToolTipIcon(this.bunifuButton2, null);
            this.bunifuToolTip1.SetToolTipTitle(this.bunifuButton2, "");
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            // 
            // reportDropdown
            // 
            this.reportDropdown.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.reportDropdown.BackColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.reportDropdown.Controls.Add(this.btnDebt);
            this.reportDropdown.Controls.Add(this.btnInventory);
            this.DropdownAnimation.SetDecoration(this.reportDropdown, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.reportDropdown.Location = new System.Drawing.Point(1056, 0);
            this.reportDropdown.Name = "reportDropdown";
            this.reportDropdown.Size = new System.Drawing.Size(117, 106);
            this.reportDropdown.TabIndex = 7;
            this.bunifuToolTip1.SetToolTip(this.reportDropdown, "");
            this.bunifuToolTip1.SetToolTipIcon(this.reportDropdown, null);
            this.bunifuToolTip1.SetToolTipTitle(this.reportDropdown, "");
            this.reportDropdown.Visible = false;
            // 
            // btnDebt
            // 
            this.btnDebt.AllowToggling = false;
            this.btnDebt.AnimationSpeed = 200;
            this.btnDebt.AutoGenerateColors = false;
            this.btnDebt.BackColor = System.Drawing.Color.Transparent;
            this.btnDebt.BackColor1 = System.Drawing.Color.Transparent;
            this.btnDebt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDebt.BackgroundImage")));
            this.btnDebt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDebt.ButtonText = "Debt";
            this.btnDebt.ButtonTextMarginLeft = 0;
            this.btnDebt.ColorContrastOnClick = 45;
            this.btnDebt.ColorContrastOnHover = 45;
            this.btnDebt.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnDebt.CustomizableEdges = borderEdges9;
            this.DropdownAnimation.SetDecoration(this.btnDebt, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.btnDebt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDebt.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnDebt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDebt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDebt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDebt.Font = new System.Drawing.Font("Futura Lt BT", 18F);
            this.btnDebt.ForeColor = System.Drawing.Color.White;
            this.btnDebt.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDebt.IconMarginLeft = 11;
            this.btnDebt.IconPadding = 10;
            this.btnDebt.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnDebt.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnDebt.IdleBorderRadius = 3;
            this.btnDebt.IdleBorderThickness = 1;
            this.btnDebt.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnDebt.IdleIconLeftImage = null;
            this.btnDebt.IdleIconRightImage = null;
            this.btnDebt.IndicateFocus = false;
            this.btnDebt.Location = new System.Drawing.Point(0, 56);
            this.btnDebt.Name = "btnDebt";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties17.BorderRadius = 3;
            stateProperties17.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties17.BorderThickness = 1;
            stateProperties17.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties17.ForeColor = System.Drawing.Color.White;
            stateProperties17.IconLeftImage = null;
            stateProperties17.IconRightImage = null;
            this.btnDebt.onHoverState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties18.BorderRadius = 3;
            stateProperties18.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties18.BorderThickness = 1;
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties18.ForeColor = System.Drawing.Color.White;
            stateProperties18.IconLeftImage = null;
            stateProperties18.IconRightImage = null;
            this.btnDebt.OnPressedState = stateProperties18;
            this.btnDebt.Size = new System.Drawing.Size(117, 44);
            this.btnDebt.TabIndex = 6;
            this.btnDebt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDebt.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.btnDebt, "");
            this.bunifuToolTip1.SetToolTipIcon(this.btnDebt, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnDebt, "");
            this.btnDebt.UseDefaultRadiusAndThickness = true;
            this.btnDebt.Click += new System.EventHandler(this.btnDebt_Click);
            // 
            // btnInventory
            // 
            this.btnInventory.AllowToggling = false;
            this.btnInventory.AnimationSpeed = 200;
            this.btnInventory.AutoGenerateColors = false;
            this.btnInventory.BackColor = System.Drawing.Color.Transparent;
            this.btnInventory.BackColor1 = System.Drawing.Color.Transparent;
            this.btnInventory.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnInventory.BackgroundImage")));
            this.btnInventory.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnInventory.ButtonText = "Inventory";
            this.btnInventory.ButtonTextMarginLeft = 0;
            this.btnInventory.ColorContrastOnClick = 45;
            this.btnInventory.ColorContrastOnHover = 45;
            this.btnInventory.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btnInventory.CustomizableEdges = borderEdges10;
            this.DropdownAnimation.SetDecoration(this.btnInventory, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.btnInventory.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnInventory.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnInventory.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnInventory.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnInventory.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnInventory.Font = new System.Drawing.Font("Futura Lt BT", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnInventory.ForeColor = System.Drawing.Color.White;
            this.btnInventory.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnInventory.IconMarginLeft = 11;
            this.btnInventory.IconPadding = 10;
            this.btnInventory.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnInventory.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnInventory.IdleBorderRadius = 3;
            this.btnInventory.IdleBorderThickness = 1;
            this.btnInventory.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnInventory.IdleIconLeftImage = null;
            this.btnInventory.IdleIconRightImage = null;
            this.btnInventory.IndicateFocus = false;
            this.btnInventory.Location = new System.Drawing.Point(0, 3);
            this.btnInventory.Name = "btnInventory";
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.BorderRadius = 3;
            stateProperties19.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties19.BorderThickness = 1;
            stateProperties19.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.ForeColor = System.Drawing.Color.White;
            stateProperties19.IconLeftImage = null;
            stateProperties19.IconRightImage = null;
            this.btnInventory.onHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties20.BorderRadius = 3;
            stateProperties20.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties20.BorderThickness = 1;
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties20.ForeColor = System.Drawing.Color.White;
            stateProperties20.IconLeftImage = null;
            stateProperties20.IconRightImage = null;
            this.btnInventory.OnPressedState = stateProperties20;
            this.btnInventory.Size = new System.Drawing.Size(117, 47);
            this.btnInventory.TabIndex = 5;
            this.btnInventory.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnInventory.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.btnInventory, "");
            this.bunifuToolTip1.SetToolTipIcon(this.btnInventory, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnInventory, "");
            this.btnInventory.UseDefaultRadiusAndThickness = true;
            this.btnInventory.Click += new System.EventHandler(this.btnInventory_Click);
            // 
            // sellDropdown
            // 
            this.sellDropdown.Anchor = System.Windows.Forms.AnchorStyles.Top;
            this.sellDropdown.BackColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.sellDropdown.Controls.Add(this.btnTabDebt);
            this.sellDropdown.Controls.Add(this.btnTabInvoice);
            this.sellDropdown.Controls.Add(this.btnTabSell);
            this.DropdownAnimation.SetDecoration(this.sellDropdown, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.sellDropdown.Location = new System.Drawing.Point(613, 0);
            this.sellDropdown.Name = "sellDropdown";
            this.sellDropdown.Size = new System.Drawing.Size(117, 170);
            this.sellDropdown.TabIndex = 5;
            this.bunifuToolTip1.SetToolTip(this.sellDropdown, "");
            this.bunifuToolTip1.SetToolTipIcon(this.sellDropdown, null);
            this.bunifuToolTip1.SetToolTipTitle(this.sellDropdown, "");
            this.sellDropdown.Visible = false;
            // 
            // btnTabDebt
            // 
            this.btnTabDebt.AllowToggling = false;
            this.btnTabDebt.AnimationSpeed = 200;
            this.btnTabDebt.AutoGenerateColors = false;
            this.btnTabDebt.BackColor = System.Drawing.Color.Transparent;
            this.btnTabDebt.BackColor1 = System.Drawing.Color.Transparent;
            this.btnTabDebt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTabDebt.BackgroundImage")));
            this.btnTabDebt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTabDebt.ButtonText = "Debt";
            this.btnTabDebt.ButtonTextMarginLeft = 0;
            this.btnTabDebt.ColorContrastOnClick = 45;
            this.btnTabDebt.ColorContrastOnHover = 45;
            this.btnTabDebt.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.btnTabDebt.CustomizableEdges = borderEdges11;
            this.DropdownAnimation.SetDecoration(this.btnTabDebt, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.btnTabDebt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTabDebt.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnTabDebt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTabDebt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTabDebt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTabDebt.Font = new System.Drawing.Font("Futura Lt BT", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnTabDebt.ForeColor = System.Drawing.Color.White;
            this.btnTabDebt.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnTabDebt.IconMarginLeft = 11;
            this.btnTabDebt.IconPadding = 10;
            this.btnTabDebt.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnTabDebt.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnTabDebt.IdleBorderRadius = 3;
            this.btnTabDebt.IdleBorderThickness = 1;
            this.btnTabDebt.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnTabDebt.IdleIconLeftImage = null;
            this.btnTabDebt.IdleIconRightImage = null;
            this.btnTabDebt.IndicateFocus = false;
            this.btnTabDebt.Location = new System.Drawing.Point(0, 106);
            this.btnTabDebt.Name = "btnTabDebt";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties21.BorderRadius = 3;
            stateProperties21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties21.BorderThickness = 1;
            stateProperties21.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties21.ForeColor = System.Drawing.Color.White;
            stateProperties21.IconLeftImage = null;
            stateProperties21.IconRightImage = null;
            this.btnTabDebt.onHoverState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties22.BorderRadius = 3;
            stateProperties22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties22.BorderThickness = 1;
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties22.ForeColor = System.Drawing.Color.White;
            stateProperties22.IconLeftImage = null;
            stateProperties22.IconRightImage = null;
            this.btnTabDebt.OnPressedState = stateProperties22;
            this.btnTabDebt.Size = new System.Drawing.Size(117, 44);
            this.btnTabDebt.TabIndex = 7;
            this.btnTabDebt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTabDebt.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.btnTabDebt, "");
            this.bunifuToolTip1.SetToolTipIcon(this.btnTabDebt, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnTabDebt, "");
            this.btnTabDebt.UseDefaultRadiusAndThickness = true;
            this.btnTabDebt.Click += new System.EventHandler(this.btnTabDebt_Click);
            // 
            // btnTabInvoice
            // 
            this.btnTabInvoice.AllowToggling = false;
            this.btnTabInvoice.AnimationSpeed = 200;
            this.btnTabInvoice.AutoGenerateColors = false;
            this.btnTabInvoice.BackColor = System.Drawing.Color.Transparent;
            this.btnTabInvoice.BackColor1 = System.Drawing.Color.Transparent;
            this.btnTabInvoice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTabInvoice.BackgroundImage")));
            this.btnTabInvoice.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTabInvoice.ButtonText = "Invoice";
            this.btnTabInvoice.ButtonTextMarginLeft = 0;
            this.btnTabInvoice.ColorContrastOnClick = 45;
            this.btnTabInvoice.ColorContrastOnHover = 45;
            this.btnTabInvoice.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges12.BottomLeft = true;
            borderEdges12.BottomRight = true;
            borderEdges12.TopLeft = true;
            borderEdges12.TopRight = true;
            this.btnTabInvoice.CustomizableEdges = borderEdges12;
            this.DropdownAnimation.SetDecoration(this.btnTabInvoice, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.btnTabInvoice.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTabInvoice.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnTabInvoice.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTabInvoice.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTabInvoice.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTabInvoice.Font = new System.Drawing.Font("Futura Lt BT", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnTabInvoice.ForeColor = System.Drawing.Color.White;
            this.btnTabInvoice.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnTabInvoice.IconMarginLeft = 11;
            this.btnTabInvoice.IconPadding = 10;
            this.btnTabInvoice.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnTabInvoice.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnTabInvoice.IdleBorderRadius = 3;
            this.btnTabInvoice.IdleBorderThickness = 1;
            this.btnTabInvoice.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnTabInvoice.IdleIconLeftImage = null;
            this.btnTabInvoice.IdleIconRightImage = null;
            this.btnTabInvoice.IndicateFocus = false;
            this.btnTabInvoice.Location = new System.Drawing.Point(0, 56);
            this.btnTabInvoice.Name = "btnTabInvoice";
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.BorderRadius = 3;
            stateProperties23.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties23.BorderThickness = 1;
            stateProperties23.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.ForeColor = System.Drawing.Color.White;
            stateProperties23.IconLeftImage = null;
            stateProperties23.IconRightImage = null;
            this.btnTabInvoice.onHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties24.BorderRadius = 3;
            stateProperties24.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties24.BorderThickness = 1;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties24.ForeColor = System.Drawing.Color.White;
            stateProperties24.IconLeftImage = null;
            stateProperties24.IconRightImage = null;
            this.btnTabInvoice.OnPressedState = stateProperties24;
            this.btnTabInvoice.Size = new System.Drawing.Size(117, 44);
            this.btnTabInvoice.TabIndex = 6;
            this.btnTabInvoice.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTabInvoice.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.btnTabInvoice, "");
            this.bunifuToolTip1.SetToolTipIcon(this.btnTabInvoice, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnTabInvoice, "");
            this.btnTabInvoice.UseDefaultRadiusAndThickness = true;
            this.btnTabInvoice.Click += new System.EventHandler(this.btnTabInvoice_Click);
            // 
            // btnTabSell
            // 
            this.btnTabSell.AllowToggling = false;
            this.btnTabSell.AnimationSpeed = 200;
            this.btnTabSell.AutoGenerateColors = false;
            this.btnTabSell.BackColor = System.Drawing.Color.Transparent;
            this.btnTabSell.BackColor1 = System.Drawing.Color.Transparent;
            this.btnTabSell.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTabSell.BackgroundImage")));
            this.btnTabSell.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTabSell.ButtonText = "Sell";
            this.btnTabSell.ButtonTextMarginLeft = 0;
            this.btnTabSell.ColorContrastOnClick = 45;
            this.btnTabSell.ColorContrastOnHover = 45;
            this.btnTabSell.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges13.BottomLeft = true;
            borderEdges13.BottomRight = true;
            borderEdges13.TopLeft = true;
            borderEdges13.TopRight = true;
            this.btnTabSell.CustomizableEdges = borderEdges13;
            this.DropdownAnimation.SetDecoration(this.btnTabSell, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.btnTabSell.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTabSell.DisabledBorderColor = System.Drawing.Color.Empty;
            this.btnTabSell.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTabSell.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTabSell.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTabSell.Font = new System.Drawing.Font("Futura Lt BT", 18F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnTabSell.ForeColor = System.Drawing.Color.White;
            this.btnTabSell.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnTabSell.IconMarginLeft = 11;
            this.btnTabSell.IconPadding = 10;
            this.btnTabSell.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnTabSell.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnTabSell.IdleBorderRadius = 3;
            this.btnTabSell.IdleBorderThickness = 1;
            this.btnTabSell.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnTabSell.IdleIconLeftImage = null;
            this.btnTabSell.IdleIconRightImage = null;
            this.btnTabSell.IndicateFocus = false;
            this.btnTabSell.Location = new System.Drawing.Point(0, 3);
            this.btnTabSell.Name = "btnTabSell";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties25.BorderRadius = 3;
            stateProperties25.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties25.BorderThickness = 1;
            stateProperties25.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties25.ForeColor = System.Drawing.Color.White;
            stateProperties25.IconLeftImage = null;
            stateProperties25.IconRightImage = null;
            this.btnTabSell.onHoverState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties26.BorderRadius = 3;
            stateProperties26.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            stateProperties26.BorderThickness = 1;
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            stateProperties26.ForeColor = System.Drawing.Color.White;
            stateProperties26.IconLeftImage = null;
            stateProperties26.IconRightImage = null;
            this.btnTabSell.OnPressedState = stateProperties26;
            this.btnTabSell.Size = new System.Drawing.Size(117, 47);
            this.btnTabSell.TabIndex = 5;
            this.btnTabSell.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTabSell.TextMarginLeft = 0;
            this.bunifuToolTip1.SetToolTip(this.btnTabSell, "");
            this.bunifuToolTip1.SetToolTipIcon(this.btnTabSell, null);
            this.bunifuToolTip1.SetToolTipTitle(this.btnTabSell, "");
            this.btnTabSell.UseDefaultRadiusAndThickness = true;
            this.btnTabSell.Click += new System.EventHandler(this.btnTabSell_Click);
            // 
            // panelControls
            // 
            this.panelControls.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panelControls.BackColor = System.Drawing.Color.Transparent;
            this.DropdownAnimation.SetDecoration(this.panelControls, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.panelControls.Location = new System.Drawing.Point(211, 41);
            this.panelControls.Name = "panelControls";
            this.panelControls.Size = new System.Drawing.Size(1012, 617);
            this.panelControls.TabIndex = 3;
            this.bunifuToolTip1.SetToolTip(this.panelControls, "");
            this.bunifuToolTip1.SetToolTipIcon(this.panelControls, null);
            this.bunifuToolTip1.SetToolTipTitle(this.panelControls, "");
            // 
            // Shadow
            // 
            this.Shadow.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.Shadow.BackColor = System.Drawing.Color.Transparent;
            this.DropdownAnimation.SetDecoration(this.Shadow, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.Shadow.Enabled = false;
            this.Shadow.Image = ((System.Drawing.Image)(resources.GetObject("Shadow.Image")));
            this.Shadow.Location = new System.Drawing.Point(174, 9);
            this.Shadow.Name = "Shadow";
            this.Shadow.Size = new System.Drawing.Size(1098, 687);
            this.Shadow.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.Shadow.TabIndex = 2;
            this.Shadow.TabStop = false;
            this.bunifuToolTip1.SetToolTip(this.Shadow, "");
            this.bunifuToolTip1.SetToolTipIcon(this.Shadow, null);
            this.bunifuToolTip1.SetToolTipTitle(this.Shadow, "");
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 65;
            this.bunifuElipse1.TargetControl = this.panelControls;
            // 
            // DropdownAnimation
            // 
            this.DropdownAnimation.AnimationType = Bunifu.UI.WinForms.BunifuAnimatorNS.AnimationType.VertSlide;
            this.DropdownAnimation.Cursor = null;
            animation1.AnimateOnlyDifferences = true;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.DropdownAnimation.DefaultAnimation = animation1;
            // 
            // bunifuToolTip1
            // 
            this.bunifuToolTip1.Active = true;
            this.bunifuToolTip1.AlignTextWithTitle = false;
            this.bunifuToolTip1.AllowAutoClose = false;
            this.bunifuToolTip1.AllowFading = true;
            this.bunifuToolTip1.AutoCloseDuration = 5000;
            this.bunifuToolTip1.BackColor = System.Drawing.SystemColors.Control;
            this.bunifuToolTip1.BorderColor = System.Drawing.Color.Gainsboro;
            this.bunifuToolTip1.ClickToShowDisplayControl = false;
            this.bunifuToolTip1.ConvertNewlinesToBreakTags = true;
            this.bunifuToolTip1.DisplayControl = null;
            this.bunifuToolTip1.EntryAnimationSpeed = 350;
            this.bunifuToolTip1.ExitAnimationSpeed = 200;
            this.bunifuToolTip1.GenerateAutoCloseDuration = false;
            this.bunifuToolTip1.IconMargin = 6;
            this.bunifuToolTip1.InitialDelay = 0;
            this.bunifuToolTip1.Name = "bunifuToolTip1";
            this.bunifuToolTip1.Opacity = 1D;
            this.bunifuToolTip1.OverrideToolTipTitles = false;
            this.bunifuToolTip1.Padding = new System.Windows.Forms.Padding(10);
            this.bunifuToolTip1.ReshowDelay = 100;
            this.bunifuToolTip1.ShowAlways = true;
            this.bunifuToolTip1.ShowBorders = false;
            this.bunifuToolTip1.ShowIcons = true;
            this.bunifuToolTip1.ShowShadows = true;
            this.bunifuToolTip1.Tag = null;
            this.bunifuToolTip1.TextFont = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuToolTip1.TextForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
            this.bunifuToolTip1.TextMargin = 2;
            this.bunifuToolTip1.TitleFont = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Bold);
            this.bunifuToolTip1.TitleForeColor = System.Drawing.Color.Black;
            this.bunifuToolTip1.ToolTipPosition = new System.Drawing.Point(0, 0);
            this.bunifuToolTip1.ToolTipTitle = null;
            // 
            // Form_Main
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1363, 784);
            this.Controls.Add(this.background);
            this.Controls.Add(this.navigationBar);
            this.DropdownAnimation.SetDecoration(this, Bunifu.UI.WinForms.BunifuTransition.DecorationType.None);
            this.DoubleBuffered = true;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "Form_Main";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Bookshop Santa Monica";
            this.navigationBar.ResumeLayout(false);
            this.navigationBar.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.background.ResumeLayout(false);
            this.panelSettings.ResumeLayout(false);
            this.reportDropdown.ResumeLayout(false);
            this.sellDropdown.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.Shadow)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForm.BunifuShadowPanel.BunifuShadowPanel navigationBar;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private Bunifu.Framework.UI.BunifuDragControl bunifuDragControl1;
        private System.Windows.Forms.Panel background;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private System.Windows.Forms.Panel panelControls;
        private System.Windows.Forms.PictureBox Shadow;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBooks;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHome;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCustomers;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEmployee;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSell;

        private Bunifu.UI.WinForms.BunifuImageButton btnSettings;
        private Bunifu.UI.WinForms.BunifuImageButton btnLogout;

        private Bunifu.UI.WinForms.BunifuTransition DropdownAnimation;
        private System.Windows.Forms.Panel sellDropdown;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTabInvoice;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTabSell;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnReport;
        private System.Windows.Forms.Panel reportDropdown;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDebt;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnInventory;
        private System.Windows.Forms.Panel panelSettings;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuToolTip bunifuToolTip1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTabDebt;

    }
}

